### ISSUE TITLE
Requiring ppx_jane in .ocamlinit slows utop to a crawl

### ISSUE THREAD

**Issue by kitfre** [janestreet/ppx_jane#1]
If I use ppx_jane in my .ocamlinit instead of camlp4o, launching utop slows to a crawl and takes upwards of a minute and then the entire session lags. For reference my .ocamlinit is
`#use "topfind";;
  #thread;;
  #camlp4o;;

  #require "core.top";;
  #require "async";;
  #require "core_extended";;

  (\* Added by OPAM. *)
 let () =
    try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
    with Not_found -> ()
  ;;

  open Core.Std;;`

**Comment by ghost** [comment]
I assume you are doing `#require "ppx_jane"`. Can you try `#ppx "ppx-jane -as-ppx"` instead?

**Comment by kitfre** [comment]
That did it, thanks!

**Comment by ghost** [comment]
OK, I added a note in the README
