### ISSUE TITLE
Missing dependency on variantslib

### ISSUE THREAD

**Issue by yminsky** [janestreet/ppx_jane#2]
When you require the `ppx_jane` package via findlib, it doesn't link in variantslib, which cases [@@deriving variants] to fail. I guess this is a missing dependency.

**Comment by ghost** [comment]
The dependency is specified in [the META of ppx_variants_conv](https://github.com/janestreet/ppx_variants_conv/blob/master/META.ab#L4). Can you give the full command line that fails to compile?

**Comment by hhugo** [comment]
@yminsky, do you still have issues ?

**Comment by yminsky** [comment]
No.
