### ISSUE TITLE
Rename to ppx_base?

### ISSUE THREAD

**Issue by yminsky** [janestreet/ppx_jane#3]
I wonder if this should be considered the package that we recommend (but don't require) people use alongside base? It might be a better naming convention, though I'm not sure it's worth the churn.

**Comment by ghost** [comment]
I was thinking to keep this package and add `ppx_base`. There are several extensions that should be only in `ppx_jane`, such as `ppx_bin_prot`

**Comment by yminsky** [comment]
Sounds good.
