### ISSUE TITLE
"Error: Reference to undefined global `Longident'" with OCaml v. 4.02.3

### ISSUE THREAD

**Issue by kuwze** [janestreet/ppx_jane#4]
Hello,

First of all I am using OCaml v. 4.02.3 and this is the output of  `% opam install ppx_jane

> [NOTE] Package ppx_jane is already installed (current version is 113.33.03).

I am trying to follow the `.ocamlinit` described here https://janestreet.github.io/installation.html and I am getting this error:

> File "/home/kuwze/.ocamlinit", line 1:
> Error: Reference to undefined global `Longident'

**Comment by hhugo** [comment]
Version `113.33.03` is two years old. I would advise you to update to OCaml 4.06.0 [1].

```
opam switch 4.06.1
eval `opam config env`
```
