### ISSUE TITLE
unconditionally disable ppx_js_style

### ISSUE THREAD

**Issue by ivg** [janestreet/ppx_jane#5]
Just adding a dependency on ppx_jane applies the style to totally independent packages, even for ocamlfind. Is it possible to unconditionally disable it and enable only when a user explicitly specified that they need it?
see https://github.com/BinaryAnalysisPlatform/bap/pull/1116

**Comment by XVilka** [comment]
Are there any updates on this?

**Comment by yminsky** [comment]
Sorry, just saw this (h/t to Anil), but I do not understand the description of the problem. Can you explain the problem more clearly?

**Comment by ivg** [comment]
When ppx_base or ppx_jane is used as a dependency, it applies the ppx_js_style not only to the dependent code (which is a problem on its own) but also to the code that is generated during the compilation. Notable examples are various protocol generators and, most importantly, findlib.dynlink that links with the target program a small piece of code that doesn't pass the js style test.  E.g., `ocamplfind opt main.ml -pkg ppx_jane -pkg findlib.dynlink -linkpkg` fails because of the bad style in the code generated by findlib. 

Given that, we are kindly asking to remove the ppx_js_style preprocessor from the, now, ppx_base driver. Especially, since your libraries are using dune and can choose freely which preprocessors they want to use.

**Comment by ghost** [comment]
> it applies the ppx_js_style not only to the dependent code (which is a problem on its own)

What do you mean by that?

> but also to the code that is generated during the compilation. Notable examples are various protocol generators and, most importantly, findlib.dynlink that links with the target program a small piece of code that doesn't pass the js style test. E.g., ocamplfind opt main.ml -pkg ppx_jane -pkg findlib.dynlink -linkpkg fails because of the bad style in the code generated by findlib.

For the piece of code generated by `findlib.dynload`, that seems like a bug in ocamlfind to me. This piece of code is entirely generated by ocamlfind and there is no reason to apply ppx rewriters to it. FTR, this is what Dune does: just like ocamlfind, it also magically generates this small piece of code when linking an executable that depends on `findlib.dynload`, and it doesn't apply ppx rewriters to it.

For other code generators, we did intend to apply `ppx_js_style` unconditionally when we initially developed it. It was to ensure that the code generated by our various ppx rewriters followed the same rules as the human written code.

You can disable `ppx_js_style` as follow with ocamlfind:

```
$ ocamlfind opt -pkg ppx_jane -ppxopt ppx_jane,'-dont-apply js_style'
```

I had a look at the `ppx_bap` package that was referenced in this PR, and I think it is the right thing to do. That will give you better control over the set of ppx rewriters you want to apply to your code.

**Comment by ivg** [comment]
> What do you mean by that?

I mean that enforcing a style is probably not a good idea, especially when this style changes on each release and prevents a perfectly valid code from being compiled. It is sort of the same as turning warnings into errors in the release build. A big no-no for me. If this style error wouldn't be a fatal error there will not be any problems with that.

> For the piece of code generated by findlib.dynload, that seems like a bug in ocamlfind to me. 

I know, I agree. The PR to fix it was submitted half a year ago (with no attention). Since then we can't move forward. That is the problem with the code base that we can't control. 

> You can disable ppx_js_style as follow with ocamlfind:

Sure, the problem is that we're using oasis with two backends, ocamlbuild and omake, which in turn use `ocamlfind`. We also have 110 packages in one big meg repo. So passing this option appropriately turned out to be quite complicated. In other words, we have explored this venue. 

> I had a look at the ppx_bap package that was referenced in this PR, and I think it is the right thing to do. That will give you better control over the set of ppx rewriters you want to apply to your code.

Yep, that is what we will end up doing. And although I still disagree with the idea of including ppx_js_style in the default set of ppx_rewriters, we will pursue our own approach in our own package. So I think we can close this issue as wontfix.

**Comment by ghost** [comment]
Totally agreed that turning warnings into errors in release build is a big no-no. Having `ppx_js_style` by default makes sense inside Jane Street, and for Jane Street open source packages as well (as discussed [here](https://github.com/janestreet/ppx_base/issues/1)). But agreed that it's not ideal for other open source projects, especially if you use it in combination with other ppx rewriters.

At this point, I think it's fair to say that `ppx_jane` and `ppx_base` are tailored for Jane Street code base and open source packages, as well as for projects that only use Jane Street ppx rewriters and want to follow our coding conventions closely. Perhaps we could introduce an intermediate set that doesn't have ppx_js_style. That would he useful to more people and doesn't seem too complicated to support.

**Comment by yminsky** [comment]
So, are there two changes needed here? One to disable ppx_js_style in release mode, and the other is to have a smaller PPX that does the same thing as ppx_jane and ppx_base, but without the style restrictions?

**Comment by drvink** [comment]
@yminsky Certainly the latter would be nice; it works around the problem demonstrated in e.g. ocaml/ocamlfind#9.

**Comment by ghost** [comment]
We ended up removing `ppx_js_style` from the opensource version of `ppx_base`. The change was made internally, should pop up on github soon and will be part of the next stable release.
